[tox]
ignore_basepython_conflict = True
skip_missing_interpreters = True
envlist =
    py{310,311,312,313,314}
    ruff
    ruff_format
    docformatter
    pydocstyle
    mypy


####### Python Test Environments #######

[testenv]
basepython = python3.13
setenv =
    TERM = xterm-256color
passenv =
    PYTHONASYNCIODEBUG
deps =
    pexpect
    pytest
    pytest-asyncio>=0.21
    pytest-cov
    pytest-timeout
    pytest-xdist
    trustme
usedevelop = True
commands =
    pytest {posargs:--strict-markers --verbose --durations=10} telix/tests


####### Linting and Formatting Environments #######

[testenv:ruff]
deps = ruff
commands =
    ruff check telix/

[testenv:ruff_format]
deps = ruff
commands = ruff format --check telix/

[testenv:docformatter]
basepython = python3.13
deps =
    docformatter>=1.7.7
    untokenize
commands =
    docformatter \
        --in-place \
        --recursive \
        --pre-summary-newline \
        --wrap-summaries=120 \
        --wrap-descriptions=120 \
        {toxinidir}/telix/

[testenv:docformatter_check]
basepython = python3.13
deps =
    docformatter>=1.7.7
    untokenize
commands =
    docformatter \
        --check \
        --diff \
        --recursive \
        --pre-summary-newline \
        --wrap-summaries=120 \
        --wrap-descriptions=120 \
        {toxinidir}/telix/

[testenv:mypy]
deps =
    mypy
commands =
    mypy telix

[testenv:pydocstyle]
deps =
    pydocstyle
    restructuredtext_lint
    doc8
    pygments
commands =
    pydocstyle --source --explain {toxinidir}/telix
    rst-lint README.rst
    doc8 --ignore-path docs/_build --ignore D000 docs

[testenv:codespell]
deps =
    codespell
commands =
    codespell --skip="*.pyc,*.log,*.debug,typescript*,htmlcov*,_build,build,*.egg-info,.tox,.git" \
              --ignore-words-list="wont,nams,flushin,thirdparty,lient,caf,alo,implementor,untils,hel,vor,ofo,drastical,dum" \
              --uri-ignore-words-list "*" \
              --summary --count

[testenv:format]
deps =
    ruff
    {[testenv:docformatter]deps}
commands =
    ruff check --fix telix/
    ruff format telix/
    {[testenv:docformatter]commands}

[testenv:lint]
deps =
    {[testenv:ruff]deps}
    {[testenv:pydocstyle]deps}
    {[testenv:codespell]deps}
commands =
    {[testenv:ruff]commands}
    {[testenv:ruff_format]commands}
    {[testenv:pydocstyle]commands}
    {[testenv:codespell]commands}


####### Documentation #######

[testenv:docs]
deps =
    -r{toxinidir}/docs/requirements.txt
usedevelop = True
commands =
    sphinx-build -W -b html {toxinidir}/docs {toxinidir}/docs/_build/html


####### Tool Configs #######

[coverage:run]
branch = True
parallel = True
source = telix
omit = telix/tests/*
relative_files = True

[coverage:report]
precision = 1
exclude_lines =
    pragma: no cover
omit = telix/tests/*

[coverage:paths]
source = telix/

[doc8]
max-line-length = 120

[pydocstyle]
ignore =
    D101,
    D102,
    D103,
    D105,
    D107,
    D203,
    D204,
    D212,
    D401

[pytest]
norecursedirs = .git .tox build
asyncio_mode = auto
log_level = debug
log_format = %(levelname)8s %(filename)s:%(lineno)s %(message)s
addopts =
    --strict-markers
    --verbose
    --capture=no
    -n auto
    -p no:benchmark
    --color=yes
    --cov
    --cov-append
    --cov-report=xml
    --disable-pytest-warnings
    --ignore=setup.py
    --ignore=.tox
    --durations=10
    --timeout=15
    --junit-xml=.tox/results.{envname}.xml
faulthandler_timeout = 30
filterwarnings =
junit_family = xunit1
