"""Bitmap font registry -- auto-generated by tools/build_fonts.py."""

import typing
import pathlib

FONT_BIN_PATH = pathlib.Path(__file__).parent / "fonts.bin"
FONT_MAGIC = b"TELX"
FONT_VERSION = 1


class FontEntry(typing.NamedTuple):
    font_id: int
    name: str
    encoding: str
    width: int
    height: int
    nglyphs: int
    data_offset: int
    data_len: int


FONT_TABLE: list[FontEntry] = [
    FontEntry(0, "CP437 English", "cp437", 8, 16, 256, 2125, 4096),
    FontEntry(1, "CP1251 Cyrillic (swiss)", "cp1251", 8, 16, 256, 6221, 4096),
    FontEntry(2, "KOI8-R Russian", "koi8-r", 8, 16, 256, 10317, 4096),
    FontEntry(3, "ISO-8859-2 Central European", "iso-8859-2", 8, 16, 256, 14413, 4096),
    FontEntry(4, "ISO-8859-4 Baltic wide (VGA 9bit)", "iso-8859-4", 8, 16, 256, 18509, 4096),
    FontEntry(5, "CP866 Russian (c)", "cp866", 8, 16, 256, 22605, 4096),
    FontEntry(6, "ISO-8859-9 Turkish", "iso-8859-9", 8, 16, 256, 26701, 4096),
    FontEntry(7, "ISO-8859-1 West European", "iso-8859-1", 8, 16, 256, 30797, 4096),
    FontEntry(8, "ISO-8859-8 Hebrew", "iso-8859-8", 8, 16, 256, 34893, 4096),
    FontEntry(9, "KOI8-U Ukrainian", "koi8-u", 8, 16, 256, 38989, 4096),
    FontEntry(10, "ISO-8859-15 West European (thin)", "iso-8859-15", 8, 16, 256, 43085, 4096),
    FontEntry(11, "ISO-8859-4 Baltic (VGA 9bit)", "iso-8859-4", 8, 16, 256, 47181, 4096),
    FontEntry(12, "KOI8-R Russian (b)", "koi8-r", 8, 16, 256, 51277, 4096),
    FontEntry(13, "ISO-8859-4 Baltic wide", "iso-8859-4", 8, 16, 256, 55373, 4096),
    FontEntry(14, "ISO-8859-5 Cyrillic", "iso-8859-5", 8, 16, 256, 59469, 4096),
    FontEntry(15, "ISO-8859-1 West European", "iso-8859-1", 8, 16, 256, 63565, 4096),
    FontEntry(16, "ISO-8859-15 West European", "iso-8859-15", 8, 16, 256, 67661, 4096),
    FontEntry(17, "CP850 Multilingual Latin I (thin)", "cp850", 8, 16, 256, 71757, 4096),
    FontEntry(18, "CP850 Multilingual Latin I", "cp850", 8, 16, 256, 75853, 4096),
    FontEntry(19, "CP865 Norwegian (thin)", "cp865", 8, 16, 256, 79949, 4096),
    FontEntry(20, "CP1251 Cyrillic", "cp1251", 8, 16, 256, 84045, 4096),
    FontEntry(21, "ISO-8859-7 Greek", "iso-8859-7", 8, 16, 256, 88141, 4096),
    FontEntry(22, "KOI8-R Russian (c)", "koi8-r", 8, 16, 256, 92237, 4096),
    FontEntry(23, "ISO-8859-4 Baltic", "iso-8859-4", 8, 16, 256, 96333, 4096),
    FontEntry(24, "ISO-8859-1 West European", "iso-8859-1", 8, 16, 256, 100429, 4096),
    FontEntry(25, "CP866 Russian", "cp866", 8, 16, 256, 104525, 4096),
    FontEntry(26, "CP437 English (thin)", "cp437", 8, 16, 256, 108621, 4096),
    FontEntry(27, "CP866 Russian (b)", "cp866", 8, 16, 256, 112717, 4096),
    FontEntry(28, "CP865 Norwegian", "cp865", 8, 16, 256, 116813, 4096),
    FontEntry(29, "CP866 Ukrainian", "cp866", 8, 16, 256, 120909, 4096),
    FontEntry(30, "ISO-8859-1 West European (thin)", "iso-8859-1", 8, 16, 256, 125005, 4096),
    FontEntry(31, "CP1131 Belarusian (swiss)", "cp1131", 8, 16, 256, 129101, 4096),
    FontEntry(32, "Commodore 64", "petscii", 8, 8, 256, 133197, 2048),
    FontEntry(33, "Commodore 64", "petscii", 8, 8, 256, 135245, 2048),
    FontEntry(34, "Commodore 128", "petscii", 8, 8, 256, 137293, 2048),
    FontEntry(35, "Commodore 128", "petscii", 8, 8, 256, 139341, 2048),
    FontEntry(36, "Atari Classic", "atascii", 8, 8, 256, 141389, 2048),
    FontEntry(37, "P0T-NOoDLEv1.0", "iso-8859-1", 8, 16, 256, 143437, 4096),
    FontEntry(38, "mO'sOulv1.0", "iso-8859-1", 8, 16, 256, 147533, 4096),
    FontEntry(39, "MicroKnightPlusv1.0", "iso-8859-1", 8, 16, 256, 151629, 4096),
    FontEntry(40, "TopazPlusa500v1.0", "iso-8859-1", 8, 16, 256, 155725, 4096),
    FontEntry(41, "MicroKnightv1.0", "iso-8859-1", 8, 16, 256, 159821, 4096),
    FontEntry(42, "Topaza500v1.0", "iso-8859-1", 8, 16, 256, 163917, 4096),
    FontEntry(43, "Mullard SAA-5050 (UK)", "iso-8859-1", 6, 10, 256, 168013, 2560),
    FontEntry(44, "Atari ST", "iso-8859-1", 8, 16, 256, 170573, 4096),
]

DEFAULT_FONT_ID = 0
